### ISSUE TITLE
Installation bootstrapping problem: Setup.hs already needs regex-compat

### ISSUE THREAD

**Issue by andreasabel** [kosmikus/lhs2tex#34]
Concerns the git-version of lhs2tex. Typing

```
  make
```

or

```
  cabal configure
```

complains about missing Text.Regex when processing Setup.hs

However,

```
  cabal install
```

works, since it pulls in regex-\* from hackage.

**Comment by kosmikus** [comment]
These days, lhs2TeX's cabal file does specify the setup file dependencies.
