### ISSUE TITLE
lhs2tex on Windows 10

### ISSUE THREAD

**Issue by thalesad** [kosmikus/lhs2tex#70]
Has anyone installed lhs2tex on Windows 10? I've looked for tutorials for all Windows versions, but I've got no success. Thanks.

**Comment by donya** [comment]
On Windows 10 I have used pre-2018 versions of Haskell Platform and "cabal install lhs2tex" to install it with no issues; it was very simple. I used it successfully with 8.0.1 for a long time and I think it worked up through 8.2.2 as well. It will not work with 8.4.2 or 8.4.3 though (someone already made a separate issue on that).

**Comment by thalesad** [comment]
Thank you, Donya. I installed HP version 8.0.1 and lhs2tex using "cabal install" as you suggested. However, I could not make Texstudio recognize .lhs files.

**Comment by donya** [comment]
I have not used Texstudio, so I don't know if lhs2tex can integrate with it easily. Whenever I have worked with lhs2tex, I have always used a very lightweight editor like TexWorks and then used a batch file to compile everything to pdf this way:

```
lhs2tex --poly SubSection.lhs > SubSection.tex
lhs2tex --poly MainFile > MainFile.tex
bibtex MainFile
makeindex MainFile
pdflatex MainFile
```

where MainFile.lhs has \include{SubSection} somewhere within it.

**Comment by thalesad** [comment]
Thanks a lot, Donya! Your approach worked fine here. I'm gonna close this issue. Thanks!
