### ISSUE TITLE
Bogus build failure under MacOS X 10.13.6 (High Sierra) and GHC 8.4.3, using commit ID: 2db1d7e0c62cb6ae7f8ed25c1540d758a9e36dfe

### ISSUE THREAD

**Issue by capn-freako** [kosmikus/lhs2tex#71]
Under MacOS X 10.13.6 (High Sierra) and GHC 8.4.3, after cloning commit ID: 2db1d7e0c62cb6ae7f8ed25c1540d758a9e36dfe, moving into the resultant directory, and executing:

`cabal install
`
I get:

> dca9047d694f:lhs2tex a594349$ cabal install
> clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
> Resolving dependencies...
> Configuring lhs2tex-1.20...
> Building lhs2tex-1.20...
> Failed to install lhs2tex-1.20
> Build log ( /Users/a594349/.cabal/logs/ghc-8.4.3/lhs2tex-1.20-KEQBNcWylmLBEz6WLKKhOh.log ):
> cabal: Entering directory '.'
> [1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
> Linking ./dist/setup/setup ...
> Configuring lhs2tex-1.20...
> clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
> Warning: No texmf tree found, polytable package cannot be installed
> Preprocessing executable 'lhs2TeX' for lhs2tex-1.20..
> Building executable 'lhs2TeX' for lhs2tex-1.20..
> [ 1 of 21] Compiling Auxiliaries      ( src/Auxiliaries.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Auxiliaries.o )
> [ 2 of 21] Compiling Document         ( src/Document.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Document.o )
> [ 3 of 21] Compiling FileNameUtils    ( src/FileNameUtils.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/FileNameUtils.o )
> [ 4 of 21] Compiling FiniteMap        ( src/FiniteMap.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/FiniteMap.o )
> [ 5 of 21] Compiling Parser           ( src/Parser.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Parser.o )
> [ 6 of 21] Compiling StateT           ( src/StateT.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/StateT.o )
> [ 7 of 21] Compiling TeXCommands      ( src/TeXCommands.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/TeXCommands.o )
> [ 8 of 21] Compiling HsLexer          ( src/HsLexer.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/HsLexer.o )
> [ 9 of 21] Compiling TeXParser        ( src/TeXParser.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/TeXParser.o )
> [10 of 21] Compiling Value            ( src/Value.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Value.o )
> [11 of 21] Compiling Directives       ( src/Directives.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Directives.o )
> [12 of 21] Compiling Verbatim         ( src/Verbatim.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Verbatim.o )
> [13 of 21] Compiling Typewriter       ( src/Typewriter.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Typewriter.o )
> [14 of 21] Compiling MathCommon       ( src/MathCommon.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/MathCommon.o )
> [15 of 21] Compiling MathPoly         ( src/MathPoly.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/MathPoly.o )
> [16 of 21] Compiling NewCode          ( src/NewCode.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/NewCode.o )
> [17 of 21] Compiling Math             ( src/Math.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Math.o )
> [18 of 21] Compiling Version          ( src/Version.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Version.o )
> [19 of 21] Compiling State            ( src/State.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/State.o )
> [20 of 21] Compiling License          ( src/License.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/License.o )
> [21 of 21] Compiling Main             ( src/Main.lhs, dist/build/lhs2TeX/lhs2TeX-tmp/Main.o )
> Linking dist/build/lhs2TeX/lhs2TeX ...
> clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
> clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
> doc/Guide2.pdf: copyFile: does not exist (No such file or directory)
> cabal: Leaving directory '.'
> cabal: Error: some packages failed to install:
> lhs2tex-1.20-KEQBNcWylmLBEz6WLKKhOh failed during the building phase. The
> exception was:
> ExitFailure 1
> 

And it appears the _lhs2TeX_ executable did not get installed:

```
dca9047d694f:lhs2tex a594349$ which lhs2TeX
dca9047d694f:lhs2tex a594349$ 

```
However, there is an executable named _lhs2TeX_ in `dist/build/lhs2TeX/`:

```
dca9047d694f:lhs2tex a594349$ ll dist/build/lhs2TeX/
total 6264
drwxr-xr-x   4 a594349  1244359605      128 Aug 26 10:53 autogen/
drwxr-xr-x   2 a594349  1244359605       64 Aug 26 10:53 doc/
-rwxr-xr-x   1 a594349  1244359605  3184400 Aug 26 10:53 lhs2TeX*
drwxr-xr-x  44 a594349  1244359605     1408 Aug 26 10:53 lhs2TeX-tmp/
-rw-r--r--   1 a594349  1244359605    12746 Aug 26 10:53 lhs2TeX.fmt
-rw-r--r--   1 a594349  1244359605     3848 Aug 26 10:53 lhs2TeX.sty

```
And it appears functional:

```
dca9047d694f:lhs2tex a594349$ dist/build/lhs2TeX/lhs2TeX --help
lhs2TeX [ options ] files

Available options:

  -h, -?       --help             get this help
  -v                              be verbose
  -V           --version          show version
               --tt               typewriter style (deprecated)
               --math             math style (deprecated)
               --poly             poly style (default)
               --markdown         markdown style
               --code             code style (deprecated)
               --newcode          new code style
               --verb             verbatim (deprecated)
               --haskell          Haskell lexer (default)
               --agda             Agda lexer
               --pre              act as ghc preprocessor
  -o file      --output=file      specify output file
               --file-directives  generate %file directives
               --no-pragmas       no LINE pragmas
  -A col       --align=col        align at <col>
  -i file      --include=file     include <file>
  -l equation  --let=equation     assume <equation>
  -s flag      --set=flag         set <flag>
  -u flag      --unset=flag       unset <flag>
  -P path      --path=path        modify search path
               --searchpath       show searchpath
               --copying          display license
               --warranty         info about warranty

dca9047d694f:lhs2tex a594349$ dist/build/lhs2TeX/lhs2TeX --version
lhs2TeX 1.20, Copyright (C) 1997-2017 Ralf Hinze, Andres Loeh

lhs2TeX comes with ABSOLUTELY NO WARRANTY;
for details type `lhs2TeX --warranty'.
This is free software, and you are welcome to redistribute it
under certain conditions; type `lhs2TeX --copying' for details.

```

**Comment by kosmikus** [comment]
Have you been installing this from Hackage? Or from the repository?

**Comment by capn-freako** [comment]
From the repository.

**Comment by kosmikus** [comment]
Then it may not be entirely unexpected. The normal build process tries to build the documentation, which looks like it could not work because no TeX installation was found:
```
Warning: No texmf tree found, polytable package cannot be installed
```

The distributed source packages (on Hackage) contain pre-built documentation.
