### ISSUE TITLE
Release a new version to Hackage

### ISSUE THREAD

**Issue by RyanGlScott** [kosmikus/lhs2tex#78]
The current Hackage version of `lhs2tex` ([1.22](http://hackage.haskell.org/package/lhs2tex-1.22)) [cannot be built with GHC 8.8](https://github.com/kosmikus/lhs2tex/pull/76), which makes it awkward to install. My current workaround is to manually clone this repo and `cabal install` it directly from source, but it would be far more convenient if these changes were uploaded to Hackage directly.

**Comment by RyanGlScott** [comment]
Ping @kosmikus.

**Comment by kosmikus** [comment]
Sorry. Done.

**Comment by RyanGlScott** [comment]
Thanks!
