### ISSUE TITLE
Manifold installation woes

### ISSUE THREAD

**Issue by goldfirere** [kosmikus/lhs2tex#88]
I have found myself unable to install, despite lots of different approaches. I have GHC 8.10.5 and cabal-install 3.4.0.0.

* `cabal install lhs2tex`

This hums along for a bit, and then fails with a parse error in HsLexer:

```
src/HsLexer.lhs:75:39: error:
    parse error on input ‘-- |impossible "string"|’
   |
75 | > string (TeX _ _)              =  "" -- |impossible "string"|
   |      
```

The problem is that the comment looks like a Haddock comment, but isn't one.

* `cabal unpack lhs2tex; cd lhs2tex; cabal install`

This yields only

```
cabal: Error: Could not find module: Version with any suffix:
["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the
module is autogenerated it should be added to 'autogen-modules'.
```

which I have no idea what to do with.

* Trying `cabal build` in my local copy of lhs2TeX works, but hits the parse error. I fix that error (and quite a few others, all around comments that look Haddocky). Eventually, the build works. But then `cabal install` says `cabal: filepath wildcard 'doc/Guide2.pdf' does not match any files.` so I'm stuck again.

* I cloned the repo. `cabal install` leads to the "autogen-modules" error above. But I try the alternative instructions to `./configure` and `make`. `make` fails not knowing about `directory` and `filepath` packages. I could probably install these manually, but I'd really prefer to have `cabal` do my installation, not `make install`, so I stop pursuing this option.

* I tried using ghc-8.8.3. This failed with the same parse error as ghc-8.10.5.

* I tried using ghc-9.0.1. Success! Oof.

I think the solution might simply be to get rid of comments that look Haddocky but aren't. Failing that, maybe increase the requirements on `base` so users know they need GHC 9?

**Comment by anfelor** [comment]
On my M1 Mac I got the current master branch (at commit 34301bed0a895691631ab3acd61808411fae0711) to build with:

```
> export C_INCLUDE_PATH="`xcrun --show-sdk-path`/usr/include/ffi"
> stack init
> stack build
> stack install
```

The first line is from https://gitlab.haskell.org/ghc/ghc/-/issues/20592#note_391266
`stack init` selected lts-19.26 which uses GHC 9.0.2

**Comment by kosmikus** [comment]
I've added working CI and made a new release officially compatible with various GHC versions. Sorry for the trouble all of you've had getting this to work in the past.

**Comment by goldfirere** [comment]
Thanks, Andres!
