### ISSUE TITLE
Error when using lhs2TeX --pre

### ISSUE THREAD

**Issue by spl** [kosmikus/lhs2tex#9]
Running "lhs2TeX --pre file.lhs" on any file reports the following error:

lhs2TeX: src/Main.lhs:(475,11)-(484,61): Non-exhaustive patterns in function select

This doesn't appear to cause any problems when used as "ghci -pgmL lhs2TeX -optL--pre".

For debugging purposes, it would be useful to be able to run "lhs2TeX --pre" as a standalone operation. If there's an bug in the source due to lhs2TeX macros, the errors reported by ghci with lhs2TeX as a preprocessor are not helpful.

Also, please add some documentation on using --pre as a standalone flag.

**Comment by kosmikus** [comment]
This is fixed (by producing a proper error message) in lhs2tex-1.25.
